name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [check, build, test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm i
      - name: ${{ matrix.script }}
        run: npm run ${{ matrix.script }}
